aldesantis/the-codeless-code

the-codeless-code/fr-abelards/case-163.txt

Removed the utility note about your own vacation and talk since it's outdated :)
If you wish to add it:
== Note de l'éditeur
<i>"The Codeless Code" prendra une brève pause pendant les deux prochaines semaines.
J'espère vous voir aux <a href="http://devday.pl">Dev&nbsp;Day&nbsp;2014</a> à Cracovie !</i>

Case 163 - FR - Vacances

---

the-codeless-code/es-galcalde/case-151.txt
the-codeless-code/es-galcalde/case-152.txt
the-codeless-code/es-galcalde/case-154.txt
the-codeless-code/es-galcalde/case-155.txt

An observation: On the case 155, the monk was poking the blob with his spoon and in the picture he was poking it with his chopsticks.

[es] Cases 154 and 155

---

the-codeless-code/fr-abelards/case-135.txt

I couldn't find a translation for "Ass-backwards"
(is it about riding an ass backwards? is it about half-assed job?)
so I put a pun of my own on "vade retro satanas".
Cheers!
PS: I've had case 128 in my drafts for a long time... but it's so full of graphic rendering references that I'll have a friend review it before, if he's willing to.

Case 135 - FR - Satanée Rétro Compatibilité

---

the-codeless-code/en-qi/case-83.txt
the-codeless-code/fr-cdlm/case-83.txt

and fix a missing quote in the original

[fr] case 83 (Consequences)

---

the-codeless-code/fr-abelards/case-144.txt

Testing with the new GitHub's quick pull requests :+1:
Well that's only PR to my fork, perhaps we should ask for quick-PRs to the forked repo?

Case 144 - FR - Mnémonique

---

the-codeless-code/fr-cdlm/case-49.txt

see discussion on commit a65e4465d6661b680612a14751b11be0f29abb29

Fix phrasing

---

the-codeless-code/fr-cdlm/case-90.txt

I side-stepped translating the caption, since the pun with naan did not
work in french.

[fr] case 90 (Not A Number)

---

the-codeless-code/fr-abelards/case-129.txt

A short and fun one, also related to my day job.
I can't believe I waited so long to translate this one!

Case 129 - FR - Pierre qui roule

---

the-codeless-code/fr-abelards/case-142.txt

I'm very glad to say I managed to make this one rhyme.
The pattern is (ABA CBC)*4 ; DDD ; EEF, EEF ; GG
If this pattern has a name, I'd like to know it.
As for the title it's from a french saying: "in the blind men's kingdom, one-eyed people are kings".
Cheers!

Case 142 - FR - Au royaume des aveugles

---

the-codeless-code/pl-adams/case-3.txt

Case 3 Polish translation

---

the-codeless-code/fr-abelards/case-139.txt

I initially understood the Thrown Coin as money you thrown OUT, but it can be money thrown AT.
So I chose the literal name "Temple of Money and Windows* ", after a french saying "throw money out the window".
Since I can't find a french saying for "shut up and take my money" I stuck with this original translation.
After all, money thrown away is not lost on everyone, and it's pretty smart to be the on the receiving end.
* we call MS Windows "Windows" so there's no such reference in FR either

Case 139 - FR - Rétroaction

---

the-codeless-code/fr-abelards/case-143.txt

Translating the Maybe was hard: "Peut-Être-arbre" looks ugly and unHaskelly.
So I kept the "Maybe-" prefix, further enhancing the geekiness and alienness.
Oh, and I couldn't make this poem rhyme, but I'm not sure if I understood it right.

Case 143 - FR - Monolithe

---

the-codeless-code/es-galcalde/case-180.txt

The title is the equivalent in spanish to the past perfect tense

[es] Case 180

---

the-codeless-code/fr-abelards/case-167.txt

I have to admit I loved the pun on basic.

Case 167 - FR - Retour aux basiques

---

the-codeless-code/fr-cdlm/case-48.txt
the-codeless-code/fr-cdlm/case-91.txt

[fr] case 91 (The Soul of Wit)

---

the-codeless-code/fr-abelards/case-182.txt

Two links on Zjing, no link on Banzen, is that right?

Case 182 - FR - Attrape-Souris

---

the-codeless-code/fr-abelards/case-171.

OK so this is real case 171.
Sorry for the inconvenience.

Case 171 - FR - Conditions initiales

---

the-codeless-code/fr-abelards/case-177.txt

Dammit! I messed up, this was 177 not 171.

Case 177 - FR - La remise à outils - renamed

---

the-codeless-code/fr-abelards/case-156.txt

Some cases have fine puns: I can translate some, add a footnote for others.
But lately when I have a difficult title, I'm more adapting than litterally translating.
Since we don't have "down the garden path" in french, I was tempted to call it "the ballad of happy coders" (after a song) but settled on "bite from the past / passing time".
Cheers!

Case 156 - FR - La morsure du passé

---

the-codeless-code/fr-abelards/case-101.txt

I'm starting a proofreading of the first cases I made.
As I found myself idle with no CodelessCode to translate, I got the urge to write some.
I'll show you when it's ready, if you wish :) cc @QilessQi

Case 101 - FR - Responsabilité - writing fixes

---

the-codeless-code/fr-abelards/case-173.txt

So it's more readable. Cheers!

Case 173 - FR - Pair Perdu - br fixes

---

the-codeless-code/fr-abelards/case-128.txt

AAAAND... with this one I think I'm done \o/
Thanks for the joy I had reading, translating and sharing, and thanks for what will come next!

Case 128 - FR - La prison des plaisirs infinis

---

the-codeless-code/fr-abelards/case-128.txt

Here it is with the illus.0.title on one line.
Thanks!

Case 128 - FR - la prison des plaisirs infinis - patch

---

the-codeless-code/fr-abelards/case-184.txt

Oh, I didn't notice the "Tagline" tag before?

Case 184 - FR - Le Jeu de la Vie

---

the-codeless-code/fr-abelards/extras/about-translator.txt

How about this kind of meta info for each author (or post)?
Cheers!

Default license added to author file - CC-BY-NC

---

the-codeless-code/fr-cdlm/extras/about-translator.txt

License added to author file

---

the-codeless-code/fr-abelards/case-106.txt

The == sections need a blank line before and after. Sorry for that.

Case 106 - FR - L'individu dans l'équipe - NdT fix

---

the-codeless-code/pl-badziew/extras/about-translator.txt

Sorry for the delay, I finally added the licensing file (see #260, #267).

[PL] Added "about translator" file.

---

the-codeless-code/fr-abelards/case-188.txt

I could translate a short title ("tough love / amour vache") but settled with a french saying ("who loves (you) well (may need to / is the best one to) chastises well".

Case 188 - FR - Qui aime bien châtie bien

---

the-codeless-code/fr-abelards/case-152.txt

The Clan of the Wolf's Bitter Breath could be an unlimited supply of stories ^^
Just noticed I never sent this PR to Alessandro! Sorry for the 2-month delay.

Case 152 - FR - Ce qui est en dessous

---

README.md

With the newly added Tagline.
BTW @qilessqi, where is the tagline displayed on the site?
Are you adding Taglines to older cases?
Also I published 2 more cases of mine (E - "No good code" and F - "Chorus")
but changed the URL to http://maitre-du-monde.fr/koans/mine.html
(I made a redirect from the link you made but not for each case... yet?).

Update README for translators

---

the-codeless-code/fr-abelards/applicant-5.txt

Aaaaaand... with that final commit, I'm 100% up to date!
The Codeless Code is fully translated in French at last.
The Applicant was a pretty nice story, I'd love to see it progress.
I was tempted to write cases of mine on Objects but I'll have to think about it a bit longer.
I got addicted to these green dots and streak of contributions on GitHub so if anyone needs help I can cut in short chunks I'll be glad to help.
Cheers to all!

applicant-5 - FR - Le Pot de Fer

---

the-codeless-code/fr-abelards/case-114.txt

And now my watch (for errors that slipped) begins.

Case 114 - FR - Caractères spéciaux - fix

---

the-codeless-code/fr-abelards/case-119.txt

Fixing a few things, notably the gender of master Suku, which I wasn't sure about when I started translating.

Case 119 - FR - Sushi - fix

---

the-codeless-code/de-andrebogus/case-10.txt
the-codeless-code/de-andrebogus/case-11.txt
the-codeless-code/de-andrebogus/case-12.txt
the-codeless-code/de-andrebogus/case-13.txt
the-codeless-code/de-andrebogus/case-14.txt
the-codeless-code/de-andrebogus/case-141.txt
the-codeless-code/de-andrebogus/case-15.txt
the-codeless-code/de-andrebogus/case-16.txt
the-codeless-code/de-andrebogus/case-17.txt
the-codeless-code/de-andrebogus/case-18.txt
the-codeless-code/de-andrebogus/case-189.txt
the-codeless-code/de-andrebogus/case-19.txt
the-codeless-code/de-andrebogus/case-20.txt
the-codeless-code/de-andrebogus/case-21.txt
the-codeless-code/de-andrebogus/case-22.txt
the-codeless-code/de-andrebogus/case-24.txt
the-codeless-code/de-andrebogus/case-25.txt
the-codeless-code/de-andrebogus/case-26.txt
the-codeless-code/de-andrebogus/case-27.txt
the-codeless-code/de-andrebogus/case-28.txt
the-codeless-code/de-andrebogus/case-29.txt
the-codeless-code/de-andrebogus/case-30.txt
the-codeless-code/de-andrebogus/case-31.txt
the-codeless-code/de-andrebogus/case-6.txt
the-codeless-code/de-andrebogus/case-7.txt
the-codeless-code/de-andrebogus/case-9.txt

Hi there,
I finally forked the github repo, and started fixing formatting + links for some translations. Also two new translations. Cheers!

two new translations and a lot of missing links restored

---

the-codeless-code/fr-abelards/case-191.txt

I now realise that in French Cancel and Undo are the same word Annuler. Oh my.

Case 191 - FR - Les Quatre Mots de la Détresse

---

the-codeless-code/de-andrebogus/case-124.txt
the-codeless-code/de-andrebogus/case-130.txt
the-codeless-code/de-andrebogus/case-158.txt

I had a bit of time on the train, so I translated a few more cases. :smile:

More translations

---

the-codeless-code/de-andrebogus/case-126.txt
the-codeless-code/de-andrebogus/case-97.txt

I even managed to make the poem of case 126 rhyme while keeping the spirit of the original. :smile:

Translations Case 97 and 126.

---

the-codeless-code/es-galcalde/case-191.txt
the-codeless-code/es-galcalde/case-192.txt

"I shall send one to your posterior... OK?"
I don't know where the question begins. And that determines the meaning of "posterior".
If the question begins in the I, it can be read as "Do you want me to send a pitchfork to your next OK?". But if the question begins in the OK, it can be read as "I'm gonna send a pitchfork to your ass, OK?"
Luckily in Spanish we have the starting question mark (¿)

[es] Case 192 (so much double-entendre)

---

the-codeless-code/de-andrebogus/case-190.txt
the-codeless-code/de-andrebogus/case-85.txt
the-codeless-code/de-andrebogus/case-90.txt

I have grep'ed for poems that I have not yet translated.

Some more translations

---

the-codeless-code/de-andrebogus/case-192.txt
the-codeless-code/de-andrebogus/case-65.txt

In case 192, I even managed to make the farmer's notes rhyme.

Two new translations

---

the-codeless-code/de-andrebogus/case-191.txt
the-codeless-code/de-andrebogus/case-192.txt
the-codeless-code/de-andrebogus/case-193.txt

And again, I managed to make it rhyme. ;-)

Some formatting and a translation of Stealthy Wombat's poem

---

the-codeless-code/de-andrebogus/case-124.txt
the-codeless-code/de-andrebogus/case-158.txt
the-codeless-code/de-andrebogus/case-187.txt
the-codeless-code/de-andrebogus/case-190.txt
the-codeless-code/de-andrebogus/case-70.txt
the-codeless-code/de-andrebogus/case-85.txt
the-codeless-code/de-andrebogus/case-90.txt
the-codeless-code/en-qi/case-187.txt

More translations and fixes

---

the-codeless-code/fr-abelards/case-194.txt

Perhaps the link on Wangohan should be in the first paragraph, not third?

Case 194 - FR - Errances

---

the-codeless-code/pt-lucasrodcosta/case-169.txt

My first contribution to The Codeless Code.

[pt] Case 169

---

the-codeless-code/de-andrebogus/case-195.txt
the-codeless-code/de-andrebogus/case-74.txt
the-codeless-code/en-qi/case-194.txt

This has a few translations and also contains an English poem for case 194. Feel free to cherry-pick if you don't want the poem.

More translations, a poem

---

the-codeless-code/es-galcalde/case-199.txt

The dichotomies should be between monosylabic words? If not, should I respect the bisyllabic lines of the stanzas?

[es] small correction and about case 200

---

the-codeless-code/fr-abelards/case-200.txt

I think @qi wants every translator to pull their hair in agony :D
That was fun, thanks!

Case 200 - FR - Le Booléen

---

the-codeless-code/fr-abelards/case-203.txt

Case 203 - FR - Dans les étoiles

---

the-codeless-code/es-galcalde/case-206.txt
the-codeless-code/es-galcalde/case-207.txt

Hash Crackers = Galletas de guiso = Crackeadores de hash

[es] Case 207

---

the-codeless-code/pl-adams/case-179.txt

Both mean "small master", but "mistrzuniu" is more probable and sounds much better in this context.

Case 179, changed "mały mistrzu" to "mistrzuniu"

---

the-codeless-code/de-andrebogus/case-208.txt

Translation case 208

---

the-codeless-code/es-galcalde/case-215.txt

I have a suggestion for a koan. Late feedback. When Client validation is required but it comes too late.
The client requested a feature in the system
I implemented the feature and the tests were succesfull in the developers environment
I released the feature in the Client's testing environment.
I asked the client to test and validate the feature and to give feedback whether if it works properly or it needs to be fixed. If it works properly, it can be released in the Client's production environment. If it needs to be fixed, the fixing will be done and again it needs to be released only in the Client's testing environment.
A WHOLE MONTH PASSES UNTIL I RECEIVE A FEEDBACK.
I don't know whether the Client had no time to test the feature until now, or he just forgot the feature.

[es] Case 215

---

the-codeless-code/fr-abelards/case-218.txt

I somehow managed to keep the names, the keywords, and rhymes.
There are plenty of adaptations one can make to sound better, changing names or adding puns for other topics.
But this is (one of) my version(s), and it works good enough.
Please, feel free to refactor or rewrite it, if only to have as much fun yourself as I did :)

Case 218 - FR - La Rétrospective Terminale

---

the-codeless-code/nl-tsluyter/case-15.txt
the-codeless-code/nl-tsluyter/case-16.txt
the-codeless-code/nl-tsluyter/case-17.txt
the-codeless-code/nl-tsluyter/case-18.txt

Added NL 15-18. Apologies for my prolonged absence.

Added NL 15-18.

---

the-codeless-code/fr-abelards/case-107.txt

That was much needed, the typos were ugly ^^

Case 107 - FR - Babel - relecture

---

the-codeless-code/fr-abelards/case-226.txt

I find it weird because you refer to Zjing as a nun a few times?
Didn't remember it happening since Zjing's promotion, but perhaps a voluntary emphasis on her learning the Master's job.
> "And how shall we manage such 'creativity'?" continued the
> nun.  "How shall we review code?  How shall we mentor?  How

Case 226 - FR - Printemps, Automne

---

the-codeless-code/fr-abelards/case-227.txt

I added a few notes on the translation of clans' names.
I hope I won't get lost on the intentions and references for the next ones to appear.
I discovered that the Roadrunner has a very funny french name: "the Great Geo-Cuckoo", and for that I am grateful :)

Case 227 - FR - Nous sommes ce que nous mangeons

---

the-codeless-code/de-andrebogus/case-234.txt

After a long hiatus, I found the Ozymandias sonnet perfect to get back to translating :smile;

Translation Case 234

---

the-codeless-code/cs-hanzik/case-1.txt
the-codeless-code/cs-hanzik/case-10.txt
the-codeless-code/cs-hanzik/case-11.txt
the-codeless-code/cs-hanzik/case-12.txt
the-codeless-code/cs-hanzik/case-13.txt
the-codeless-code/cs-hanzik/case-14.txt
the-codeless-code/cs-hanzik/case-15.txt
the-codeless-code/cs-hanzik/case-16.txt
the-codeless-code/cs-hanzik/case-17.txt
the-codeless-code/cs-hanzik/case-18.txt
the-codeless-code/cs-hanzik/case-19.txt
the-codeless-code/cs-hanzik/case-2.txt
the-codeless-code/cs-hanzik/case-20.txt
the-codeless-code/cs-hanzik/case-21.txt
the-codeless-code/cs-hanzik/case-22.txt
the-codeless-code/cs-hanzik/case-23.txt
the-codeless-code/cs-hanzik/case-24.txt
the-codeless-code/cs-hanzik/case-25.txt
the-codeless-code/cs-hanzik/case-26.txt
the-codeless-code/cs-hanzik/case-27.txt
the-codeless-code/cs-hanzik/case-28.txt
the-codeless-code/cs-hanzik/case-29.txt
the-codeless-code/cs-hanzik/case-3.txt
the-codeless-code/cs-hanzik/case-4.txt
the-codeless-code/cs-hanzik/case-5.txt
the-codeless-code/cs-hanzik/case-6.txt
the-codeless-code/cs-hanzik/case-7.txt
the-codeless-code/cs-hanzik/case-8.txt
the-codeless-code/cs-hanzik/case-9.txt

Hi there, this is my first attempt to contribute to The Codeless Code - 29 koans translated to Czech language. 
If there is something to be fixed, let me know and I will look into it.
Cheers!

Cases 1 to 29 - CS

---

the-codeless-code/fr-luke/case-230.txt
the-codeless-code/fr-luke/extras/about-translator.txt

This is the first time I translate a case entirely, maybe a bit of review from a fellow french would help. That's also why I made only one at the moment. If it seems OK the next PR will have more.

Case 238 fr

---

the-codeless-code/fr-meowcate/case-230.txt
the-codeless-code/fr-meowcate/case-231.txt
the-codeless-code/fr-meowcate/case-232.txt
the-codeless-code/fr-meowcate/case-233.txt
the-codeless-code/fr-meowcate/case-234.txt

Case 230 has been translated because I found some spelling mistakes and errors from another translator.
Case 234 has been translated trying to be a sonnet itself and not a simple translation, keeping the original meaning as much as possible while using rhyms, correct syllabes count, and _Ozymandias_ unusual rhym schem.

FR - Cases 230 to 234

---

the-codeless-code/fr-abelards/case-194.txt
the-codeless-code/fr-abelards/case-217.txt

Hi Alessandro and Qi, it's been a long time but I hope there's still some activity here :)
I missed a whole paragraph on case 194 so I'm now sending the fix.
Cheers,

Case 194 - FR - Errances - fix

---

the-codeless-code/fr-abelards/case-218.txt

I just noticed the newlines are squashed.

Adding newlines
